name: RandomTp
version: '${project.version}'
main: pe.edu.utp.plugins.randomtp.RandomTp
api-version: 1.19
authors:
  - luis
  - jonathan
  - pierosa
  - daulr
description: "Este plugin te manda a sitios random."
commands:
  hello:
    permission: randomtp.commands.hello
    permission-message: "No tienes permisos prro"
    usage: "Este comando se usa asi mira: /hello world"
    description: "Este comando saluda."
    aliases:
      - world
  luiscmd:
    permission: randomtp.commands.luiscmd
    description: "Este comando sirve para nada"
  utp:
    permission: randomtp.commands.utp
    description: "teletransporta a otras dimensiones"
  irwin:
    permission: randomtp.commands.utp
    description: "En proceso"
  randomtp:
    permission: randomtp.commands.randomtp
    permission-message: "No puedes usar este comando"
    aliases:
      - rtp
      - randomteleport
