name: RandomTp
version: '${project.version}'
main: pe.edu.utp.plugins.randomtp.PLUGIN
api-version: 1.19
authors:
  - luis
  - jonathan
  - pierosa
  - daulr
description: "Este plugin te manda a sitios random."
depend:
  - CommandAPI
commands:
  hello:
    permission: randomtp.commands.hello
    permission-message: "No tienes permisos prro"
    usage: "Este comando se usa asi mira: /hello world"
    description: "Este comando saluda."
    aliases:
      - world
  luiscmd:
    permission: randomtp.commands.luiscmd
    description: "Este comando sirve para nada"

  utp:
    permission: randomtp.commands.utp
    description: "no lo sé aún"
  irwin:
    permission: randomtp.commands.utp
    description: "En proceso"
